config/routes.rb
Rails.application.routes.draw do

	root "gossips#home"
	resources :gossips

	get "/new", to: "gossips#new"
	get "/index", to: "gossips#index"
	get "/gossips", to: "gossips#index"
	get "/edit", to: "gossips#edit"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController


  def index
  	@gossips = Gossip.all
  end

  def create
  	@gossip = Gossip.new()
  if @gossip.save
    redirect_to @gossip
  else
    render 'new'
  end
  end
 
  def update
  	@gossip = Gossip.find(params[:id])
 
  if @gossip.update(gossip_params)
    redirect_to @gossip
  else
    render 'edit'
  end
  end

  def destroy
  	@gossip = Gossip.delete
  	redirect_to @gossip
  end

  def show
  	@gossip = Gossip.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/views/gossips/edit.html.erb
<h1>Editer</h1>

<%= form_tag (gossips_path) do %>
 
  <%= label_tag 'email', 'Email' %>
  <%= text_field_tag 'anonymous_author' %>
 
  <%= label_tag 'mon gossip', 'Mon gossip' %>
  <%= text_area_tag 'content' %>
 
  <%= submit_tag "Editer le gossip"%>

  <%= link_to 'Clique pour détruire', @gossip, method: :delete %>
<% end %>

app/views/gossips/home.html.erb
<h1>Hello !</h1>

<%= link_to("Voir les derniers gossips", gossips_path) %>

app/views/gossips/index.html.erb
<h1>Listing gossips</h1>
 
<table>
  <tr>
    <th>Email</th>
    <th>Content</th>
  </tr>
 
  <% @gossips.each do |gossip| %>
    <tr>
      <td><%= gossip.anonymous_author %></td>
      <td><%= gossip.content %></td>
      <td><%= link_to 'Montrer le gossip', gossip_path(gossip) %></td>
      <td><%= link_to 'Clique pour détruire', gossip_path(gossip), method: :delete %></td>
    </tr>
  <% end %>
</table>

app/views/gossips/new.html.erb
<h1>Raconte nous ton gossip !</h1>

<%= form_tag (gossips_path) do %>
 
  <%= label_tag 'email', 'Email' %>
  <%= text_field_tag 'anonymous_author' %>
 
  <%= label_tag 'mon gossip', 'Mon gossip' %>
  <%= text_area_tag 'content' %>
 
  <%= submit_tag "Balancer mon gossip"%>
<% end %>

app/views/gossips/show.html.erb
<p><%= @gossip.content %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>